### ISSUE TITLE
Unselecting all engines keeps those not currently listed in the sidebar (because they're broken?)

### ISSUE THREAD

**Issue by linusg** [CanadaHonk/test262.fyi#25]
<img width="595" alt="image" src="https://github.com/CanadaHonk/test262.fyi/assets/19366641/cceb0bc6-ab84-4632-a6ff-2e238cfa3de0">

**Comment by nektro** [comment]
this should likely be fixed now since I fixed engine failures preemptively causing others to not run

**Comment by CanadaHonk** [comment]
If an engine fails it'll still not show up in the sidebar so should probably still be addressed, just low priority.
